version: '3.8'

services:
  frontend:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - alectrion-network
    ports:
      - 3000:3000
    command: bash -c "yarn && yarn build && yarn start"

networks:
  alectrion-network:
    external: true
